Repository inseq-team/inseq, pull requests merged in 2023-01, with the labels that each got.

#148 Basic Attention attribution
  .gitignore
  CODE_OF_CONDUCT.md
  Makefile
  README.md
  docs/source/examples/quickstart.rst
  docs/source/index.rst
  docs/source/main_classes/feature_attribution.rst
  inseq/attr/feat/__init__.py
  inseq/attr/feat/attention_attribution.py
  inseq/attr/feat/attribution_utils.py
  inseq/attr/feat/gradient_attribution.py
  inseq/attr/feat/ops/__init__.py
  inseq/attr/feat/ops/basic_attention.py
  inseq/data/attribution.py
  inseq/data/viz.py
  inseq/models/attribution_model.py
  inseq/models/decoder_only.py
  inseq/models/encoder_decoder.py
  inseq/models/huggingface_model.py
  inseq/utils/misc.py
  inseq/utils/typing.py
  poetry.lock
  pyproject.toml
  requirements-dev.txt
  requirements.txt
  tests/__init__.py
  tests/attr/feat/ops/test_attention_utils.py
  tests/models/test_huggingface_model.py
Labels: enhancement

#157 Minor fixes to 0.3.2
  .github/.stale.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release-drafter.yml
  .github/workflows/greetings.yml
  .github/workflows/release-drafter.yml
  CONTRIBUTING.md
  README.md
  inseq/attr/feat/attribution_utils.py
  inseq/attr/feat/feature_attribution.py
  inseq/data/attribution.py
  inseq/models/attribution_model.py
  inseq/models/huggingface_model.py
  inseq/utils/__init__.py
  inseq/utils/errors.py
  inseq/utils/misc.py
  inseq/utils/serialization.py
  inseq/utils/torch_utils.py
  inseq/utils/typing.py
  poetry.lock
  pyproject.toml
  requirements-dev.txt
  requirements.txt
  setup.cfg
  tests/data/test_attribution.py
  tests/inference_commons.py
Labels: bug, documentation, enhancement

#159 `ruff` stylechecking
  .pre-commit-config.yaml
  Makefile
  inseq/attr/__init__.py
  inseq/attr/attribution_decorators.py
  inseq/attr/feat/__init__.py
  inseq/attr/feat/attention_attribution.py
  inseq/attr/feat/attribution_utils.py
  inseq/attr/feat/feature_attribution.py
  inseq/attr/feat/gradient_attribution.py
  inseq/attr/feat/ops/__init__.py
  inseq/attr/feat/ops/basic_attention.py
  inseq/attr/feat/ops/discretized_integrated_gradients.py
  inseq/attr/feat/ops/monotonic_path_builder.py
  inseq/commands/attribute.py
  inseq/commands/attribute_dataset.py
  inseq/commands/base.py
  inseq/commands/cli.py
  inseq/data/__init__.py
  inseq/data/aggregator.py
  inseq/data/attribution.py
  inseq/data/batch.py
  inseq/data/data_utils.py
  inseq/data/viz.py
  inseq/models/__init__.py
  inseq/models/attribution_model.py
  inseq/models/decoder_only.py
  inseq/models/encoder_decoder.py
  inseq/models/huggingface_model.py
  inseq/models/model_decorators.py
  inseq/utils/__init__.py
  inseq/utils/argparse.py
  inseq/utils/cache.py
  inseq/utils/errors.py
  inseq/utils/import_utils.py
  inseq/utils/misc.py
  inseq/utils/registry.py
  inseq/utils/serialization.py
  inseq/utils/torch_utils.py
  inseq/utils/typing.py
  poetry.lock
  pyproject.toml
  requirements-dev.txt
  setup.cfg
  tests/__init__.py
  tests/attr/feat/ops/test_attention_utils.py
  tests/attr/feat/ops/test_monotonic_path_builder.py
  tests/data/test_aggregator.py
  tests/models/test_huggingface_model.py
Labels: enhancement, dev qol
